from __future__ import annotations

import os
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from .config import Manifest
from .runtime import resolve_hf_command, run_command


@dataclass(slots=True)
class PublishHFReport:
    ok: bool
    repo_id: str
    package_dir: str
    model_card_path: str
    commands: list[list[str]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class PublishModelCardHFReport:
    ok: bool
    repo_id: str
    output_path: str
    command: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


_AUTOGENERATED_MODEL_CARD_MARKER = "<!-- AUTOGENERATED HERETIC-TO-ONNX MODEL CARD -->"


def _capability_superset(manifest: Manifest) -> list[str]:
    if manifest.architecture == "qwen3_5_conditional_generation":
        return ["text", "image", "video"]
    if manifest.architecture == "gemma4_conditional_generation":
        return ["text", "image", "audio", "video"]
    return list(dict.fromkeys(manifest.modalities))


def _format_modality_list(modalities: list[str]) -> str:
    return ", ".join(f"`{modality}`" for modality in modalities) if modalities else "`text`"


def _related_repo_id(repo_id: str, *, want_v2: bool) -> str:
    owner, name = repo_id.split("/", 1)
    is_v2 = name.endswith("-v2")
    if want_v2:
        related_name = name if is_v2 else f"{name}-v2"
    else:
        related_name = name[:-3] if is_v2 else name
    return f"{owner}/{related_name}"


def _capability_section(manifest: Manifest, repo_id: str) -> list[str]:
    supported = [item for item in _capability_superset(manifest) if item in manifest.modalities]
    missing = [item for item in _capability_superset(manifest) if item not in manifest.modalities]
    enhanced = [item for item in supported if item not in {"text", "image"}]
    base_capabilities = [item for item in supported if item in {"text", "image"}]
    is_v2 = repo_id.split("/")[-1].endswith("-v2")
    sibling_repo_id = _related_repo_id(repo_id, want_v2=not is_v2)
    sibling_url = f"https://huggingface.co/{sibling_repo_id}"

    lines = [
        "## Capabilities",
        f"- Supported inputs: {_format_modality_list(supported)}",
    ]
    if missing:
        lines.append(f"- Not included in this package: {_format_modality_list(missing)}")

    lines.extend(["", "## Version Notes"])
    if is_v2:
        lines.extend(
            [
                "- This is the enhanced browser `v2` package for this model family.",
                f"- Compared to the v1 package at [{sibling_repo_id}]({sibling_url}), it adds support for {_format_modality_list(enhanced) if enhanced else 'the enhanced multimodal runtime contract'}.",
                f"- The lighter v1 package remains available at [{sibling_repo_id}]({sibling_url}) if you only need {_format_modality_list(base_capabilities)}.",
            ]
        )
    else:
        lines.extend(
            [
                "- This is the stable v1 browser package.",
                f"- For the enhanced multimodal variant, see [{sibling_repo_id}]({sibling_url}).",
            ]
        )
        if missing:
            lines.append(f"- The v2 package adds {_format_modality_list(missing)} for this model family.")
    return lines


def _default_model_card(manifest: Manifest, repo_id: str) -> str:
    title = repo_id.split("/")[-1]
    architecture_label = manifest.expected_architecture
    sessions = [f"- `{Path(path).name}`" for path in manifest.expected_onnx_files if path.endswith(".onnx")]
    if manifest.architecture == "gemma4_conditional_generation":
        summary = "Browser-oriented ONNX export of a Gemma 4 Heretic checkpoint packaged for WebGPU / Transformers.js."
    elif manifest.architecture == "qwen3_5_conditional_generation":
        summary = "Browser-oriented ONNX export of a Qwen3.5 Heretic checkpoint packaged for WebGPU / Transformers.js."
    else:
        summary = "Browser-oriented ONNX export packaged for WebGPU / Transformers.js."
    return "\n".join(
        [
            _AUTOGENERATED_MODEL_CARD_MARKER,
            f"# {title}",
            "",
            summary,
            "",
            *_capability_section(manifest, repo_id),
            "",
            "## Provenance",
            f"- Source model: `{manifest.source_model_id}`",
            f"- Base model for inherited processor assets: `{manifest.base_model_id}`",
            f"- Architecture family: `{manifest.architecture}`",
            f"- Expected architecture: `{architecture_label}`",
            f"- Target dtype: `{manifest.target_dtype}`",
            f"- Target device: `{manifest.target_device}`",
            "",
            "## Expected ONNX Sessions",
            *sessions,
            "",
            "## Usage",
            "Load this repo with Transformers.js using the model's `transformers.js_config` metadata and WebGPU backend.",
            "",
        ]
    )


def _model_card_metadata(manifest: Manifest, repo_id: str) -> str:
    architecture_tags = {
        "gemma4_conditional_generation": ["gemma4"],
        "qwen3_5_conditional_generation": ["qwen3.5-vl"],
    }
    tags = [
        "onnx",
        "webgpu",
        "transformers",
        "transformers.js",
        "quantized",
        *manifest.modalities,
        *architecture_tags.get(manifest.architecture, []),
    ]
    lines = [
        "---",
        "library_name: transformers",
        f"base_model: {manifest.source_model_id}",
        "tags:",
        *[f"- {tag}" for tag in tags],
        "---",
        "",
    ]
    return "\n".join(lines)


def _ensure_model_card(manifest: Manifest, package_dir: Path, repo_id: str) -> Path:
    model_card_path = package_dir / "README.md"
    metadata = _model_card_metadata(manifest, repo_id)
    model_card_path.write_text(metadata + _default_model_card(manifest, repo_id), encoding="utf-8")
    return model_card_path


def write_model_card(
    manifest: Manifest,
    *,
    output_path: str | Path,
    repo_id: str | None = None,
) -> Path:
    resolved_output_path = Path(output_path).expanduser().resolve()
    resolved_output_path.parent.mkdir(parents=True, exist_ok=True)
    resolved_repo_id = repo_id or manifest.target_repo_id
    metadata = _model_card_metadata(manifest, resolved_repo_id)
    resolved_output_path.write_text(
        metadata + _default_model_card(manifest, resolved_repo_id),
        encoding="utf-8",
    )
    return resolved_output_path


def publish_hf(
    manifest: Manifest,
    *,
    package_dir: str | Path,
    repo_id: str | None = None,
    private: bool = False,
    num_workers: int = 8,
) -> PublishHFReport:
    resolved_package_dir = Path(package_dir).expanduser().resolve()
    if not resolved_package_dir.exists():
        raise FileNotFoundError(f"package directory does not exist: {resolved_package_dir}")

    resolved_repo_id = repo_id or manifest.target_repo_id
    model_card_path = _ensure_model_card(manifest, resolved_package_dir, resolved_repo_id)
    hf_command = resolve_hf_command()

    create_command = [*hf_command, "repos", "create", resolved_repo_id, "--type", "model", "--exist-ok"]
    if private:
        create_command.append("--private")

    upload_command = [
        *hf_command,
        "upload-large-folder",
        resolved_repo_id,
        str(resolved_package_dir),
        "--type",
        "model",
        "--num-workers",
        str(num_workers),
        "--no-bars",
    ]

    report = PublishHFReport(
        ok=True,
        repo_id=resolved_repo_id,
        package_dir=str(resolved_package_dir),
        model_card_path=str(model_card_path),
        commands=[create_command, upload_command],
    )

    if not os.environ.get("HF_TOKEN"):
        report.ok = False
        report.warnings.append("HF_TOKEN is not set; Hugging Face upload will fail")
        return report

    run_command(create_command, cwd=manifest.manifest_dir)
    report.notes.append(f"ensured Hugging Face model repo exists: {resolved_repo_id}")

    run_command(upload_command, cwd=manifest.manifest_dir)
    report.notes.append(f"uploaded package directory to Hugging Face: {resolved_package_dir}")

    return report


def publish_model_card_hf(
    manifest: Manifest,
    *,
    output_path: str | Path,
    repo_id: str | None = None,
) -> PublishModelCardHFReport:
    resolved_repo_id = repo_id or manifest.target_repo_id
    resolved_output_path = write_model_card(
        manifest,
        output_path=output_path,
        repo_id=resolved_repo_id,
    )
    hf_command = resolve_hf_command()
    upload_command = [
        *hf_command,
        "upload",
        resolved_repo_id,
        str(resolved_output_path),
        "README.md",
        "--repo-type",
        "model",
    ]

    report = PublishModelCardHFReport(
        ok=True,
        repo_id=resolved_repo_id,
        output_path=str(resolved_output_path),
        command=upload_command,
    )

    if not os.environ.get("HF_TOKEN"):
        report.ok = False
        report.warnings.append("HF_TOKEN is not set; Hugging Face upload will fail")
        return report

    run_command(upload_command, cwd=manifest.manifest_dir)
    report.notes.append(f"uploaded README.md to Hugging Face repo: {resolved_repo_id}")
    return report
